version: "3.7"

services:
  api:
    build: .
    container_name: api
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    command: bash -c "wait-for-it -t 15 -s pgdb:5432 -- ./run.sh"

  pgdb:
    image: postgres:12-alpine
    container_name: pgdb
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  celery:
    container_name: celery
    env_file:
      - .env
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - api
      - redis
    command: celery -A core worker -l INFO

  celery_beat:
    container_name: celery_beat
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - celery
    command: celery -A core beat -l INFO

  redis:
    container_name: redis
    image: redis:alpine


volumes:
  pgdata:
