version: "3.7"

services:
  api:
    build: .
    container_name: api
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    command: bash -c "wait-for-it -t 15 -s pgdb:5432 -- ./run.sh"

  pgdb:
    image: postgres:12-alpine
    container_name: pgdb
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
