# Generated by Django 3.2.8 on 2021-10-05 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asn', models.IntegerField()),
                ('isp', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('plural', models.CharField(max_length=30)),
                ('symbol', models.CharField(max_length=10)),
                ('symbol_native', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('native', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tz_id', models.CharField(max_length=50)),
                ('current_time', models.DateTimeField(auto_now_add=True)),
                ('gmt_offset', models.IntegerField()),
                ('code', models.CharField(max_length=10)),
                ('is_daylight_saving', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoname_id', models.IntegerField()),
                ('capital', models.CharField(max_length=30)),
                ('country_flag', models.CharField(max_length=100)),
                ('country_flag_emoji', models.CharField(max_length=10)),
                ('country_flag_emoji_unicode', models.CharField(max_length=30)),
                ('calling_code', models.CharField(max_length=10)),
                ('is_eu', models.BooleanField(default=False)),
                ('languages', models.ManyToManyField(to='geolocation.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Geolocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=10)),
                ('continent_code', models.CharField(max_length=10)),
                ('continent_name', models.CharField(max_length=30)),
                ('country_code', models.CharField(max_length=10)),
                ('country_name', models.CharField(max_length=30)),
                ('region_code', models.CharField(max_length=10)),
                ('region_name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('zip', models.CharField(max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('connection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geolocation.connection')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geolocation.currency')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geolocation.location')),
                ('time_zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geolocation.timezone')),
            ],
        ),
    ]
