# Generated by Django 3.2.8 on 2021-10-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geolocation',
            name='connection',
        ),
        migrations.RemoveField(
            model_name='geolocation',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='geolocation',
            name='time_zone',
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='continent_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='continent_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='country_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='country_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='ip',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='region_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='region_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='zip',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='native',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='calling_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='capital',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='country_flag',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='country_flag_emoji',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='country_flag_emoji_unicode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='geoname_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='is_eu',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.DeleteModel(
            name='Connection',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='TimeZone',
        ),
    ]
