# Generated by Django 3.2.8 on 2021-10-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0002_auto_20211007_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
